services: 
    menu.menu_builder:
        class: RMT\SiteManagment\MenuBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory","@event_dispatcher"]

    menu.user_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: menu.menu_builder
        factory_method: createUserMenu
        tags:
            - { name: knp_menu.menu, alias: user_menu } # The alias is what is used to retrieve the menu