parameters:
#    rmt_time_scheduling_weekly_grid.example.class: RMT\TimeScheduling\WeeklyGridBundle\Example

services:
#    rmt_time_scheduling_weekly_grid.example:
#        class: %rmt_time_scheduling_weekly_grid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
