parameters:
#    rmt_time_scheduling_working_hours.example.class: RMT\TimeScheduling\WorkingHoursBundle\Example

services:
#    rmt_time_scheduling_working_hours.example:
#        class: %rmt_time_scheduling_working_hours.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
