RMT\TimeScheduling\Model\DayInterval:
    constraints:
        - Callback:
            methods:
                -    [RMT\TimeScheduling\DayIntervalValidator, isValidInterval]
                -    [RMT\TimeScheduling\DayIntervalValidator, isUniqueDay]
